package core.model.gameplay.gameobjects;

public enum GameObjInstanceKind {

    LOOT,
    WALL, TREE, ICEWALL,
    ARROW, FIREBALL, THORN, STONE,
    BANDIT, BANDITARCHER, BANDITBOSS,
    GOLEM, GOLEMTINY, GOLEMBOSS,
    SKELETON, SKELETONMAGE,
    FIREELEMENTAL, WATERELEMENTAL,
    VAMPIRE,
    HERO

}