package core.model.gameplay.gameobjects;

public enum GameObjInstanceKind {

    LOOT,
    WALL, TREE, ICEWALL, TREEBIG, ROCK,
    ARROW, FIREBALL, THORN, STONE, WATERBALL, VAMPIRICKNIFE, DARKFLAME,
    BANDIT, BANDITARCHER, BANDITBOSS,
    GOLEM, GOLEMTINY, GOLEMBOSS,
    SKELETON, SKELETONMAGE,
    FIREELEMENTAL, WATERELEMENTAL,
    VAMPIRE,
    HERO,
    WANDERER

}